const CUSTOM_PROTOCOL = 'browser';
const consts = {
  CUSTOM_PROTOCOL,
  NEW_TAB: `${CUSTOM_PROTOCOL}://newtab`,
  OTHER_TAB: `${CUSTOM_PROTOCOL}://othertab`,
  TOKEN_KEY: 'token',
  USER_KEY: 'user',
  MASTER_PASSWORD_KEY: 'master-password',
  WINDOW_STATE_KEY: 'window-state',
  SESSIONS_KEY: 'sessions',
  INTEGRATIONS_KEY: 'integrations',
  PAYMENT_DATA_KEY: 'payment-data',
  PORTAL_DATA_KEY: 'portal-data',
  PROXY_PORTAL_DATA_KEY: 'proxy-portal-data',
  SITES_CREDENTIALS_KEY: 'sites-credentials',
  BOOKMARKS_KEY: 'bookmarks',
  PREFERENCES_KEY: 'preferences',
  POPUP_ID: 't-o-popup',
  IMPORTANT_URLS: [
    '*://*.ticketmaster.com/*',
    '*://*.auth.ticketmaster.com/*',
    '*://*.livenation.com/*',
    '*://*.ticketweb.com/*',
    '*://*.eventbrite.com/*',
    '*://*.etix.com/*',
  ],
  CHECKOUT_TIMER_HOSTNAMES: [
    'checkout.ticketmaster.com',
    'www.ticketmaster.com',
    'www.ticketmaster.co.uk',
    'www.ticketmaster.com.au',
    'www.ticketmaster.co.nz',
    'www.ticketmaster.ie',
  ],
  AUTH_URLS: {
    patterns: [
      '*://auth.ticketmaster.com/json/sign-in',
    ],
    regexps: [
      /https?:\/\/auth.ticketmaster.com\/json\/sign-in/,
    ]
  },
  BLOCK_RESOURCE_URLS: {
    patterns: [
      '*://iphey.com/Wxu2tK/Qa87vp/*',
      // '*://pixel.tapad.com/*',
      // '*://tr.snapchat.com/*',
      // '*://axs.demdex.net/*',
      // '*://dpm.demdex.net/*',
      // '*://cdn.evgnet.com/*',
      // '*://rumcdn.geoedge.be/*',
      // '*://get.s-onetag.com/*',
      // '*://privacy-policy.truste.com/*',
      // '*://secure-us.imrworldwide.com/*',
      // '*://static.clicktripz.com/*',
      // '*://htlb.casalemedia.com/*',
      // '*://ib.adnxs.com/*',
      // '*://fastlane.rubiconproject.com/*',
      // '*://static.discovery-prod.axs.com/axs/bundles/aegaxs/images/*',
      // '*://www.googletagmanager.com/*',
      // '*://chat.satis.fi/*'
    ],
    regexps: [
      /https?:\/\/iphey.com\/Wxu2tK\/Qa87vp/,
      // /https?:\/\/tr.snapchat.com/,
      // /https?:\/\/pixel.tapad.com/,
      // /https?:\/\/axs.demdex.net/,
      // /https?:\/\/dpm.demdex.net/,
      // /https?:\/\/cdn.evgnet.com/,
      // /https?:\/\/rumcdn.geoedge.be/,
      // /https?:\/\/get.s-onetag.com/,
      // /https?:\/\/privacy-policy.truste.com/,
      // /https?:\/\/secure-us.imrworldwide.com/,
      // /https?:\/\/static.clicktripz.com/,
      // /https?:\/\/htlb.casalemedia.com/,
      // /https?:\/\/ib.adnxs.com/,
      // /https?:\/\/fastlane.rubiconproject.com/,
      // /https?:\/\/static.discovery-prod.axs.com\/axs\/bundles\/aegaxs\/images/,
      // /https?:\/\/www.googletagmanager.com/,
      // /https?:\/\/chat.satis.fi/,
      
    ]
    
  },
  ///',s3-us-west-2.amazonaws.com,*.paciolan.com,*.livenation.*,epsf.ticketmaster.ca,epsf.livenation.com,checkout.ticketmaster.ca,https://checkout.ticketmaster.com,services.ticketmaster.com,https://services.ticketmaster.ca,ccp.tmconst.com,venue.tmol.co, https://venue.tmol.co, services.livenation.com, https://services.livenation.com,epsf.ticketmaster.com'
  ///,s3-us-west-2.amazonaws.com,*.paciolan.com,checkout.ticketmaster.ca,https://checkout.ticketmaster.com,venue.tmol.co, https://venue.tmol.co, services.livenation.com, https://services.livenation.com
  ///',*.google.com,gstatic.com,googleapis.com,auth.ticketmaster.com,s3-us-west-2.amazonaws.com,*.paciolan.com,checkout.ticketmaster.*,https://checkout.ticketmaster.*,services.ticketmaster.*,https://services.ticketmaster.*,ccp.tmconst.com,venue.tmol.co, https://venue.tmol.co, services.livenation.*, https://services.livenation.*,epsf.ticketmaster.*',
  ///api.axs.com,
  IMPLIMENT_URLS:',identity.ticketmaster.*,auth.ticketmaster.*,*.eu-west-1.*,checkout.ticketmaster.*',
  ERROR_STATUS_CODES_SET: new Set([401, 403, 409, 416, 456, 506]), // 405 - captcha
  IGNORE_ERRORS_URLS: [
    /https?:\/\/www.eventbrite.com\/api\/v3\/users\/me/
  ],
  SEARCH_ENGINE: 'https://www.duckduckgo.com/?q=',
  PRELOAD_PATH: 'build/preload.js',
  AUTO_CARTING_MODAL_URL: 'https://www.eventbrite.com/checkout-external?eid=',
  BROWSER_TOP_BORDER_HEIGHT_PX: 104,
  server: {
    routes: {
      API_PROXIES: '/api/browser-licenses/',
      CHECK_TOKEN: '/users/token/',
      LOGIN: '/users/login/',
      TRAFFIC_LIMITS: '/users/traffic-limits/',
      INTEGRATIONS: '/integrations/',
      PAYMENT: '/payment-data/',
      MASTER_PASSWORD: '/users/master-password/',
      MPDECODE: '/users/mpDecode/',
      RANDOM_SESSION: '/sessions/random/',
      SESSIONS: '/sessions/',
      USAGE: '/usage/',
      FINGERPRINTS: '/fingerprints/',
      SMS_CONNECT: '/sms/connect/',
      SAVED_CREDENTIALS: '/saved-credentials/'
    },
  },
  messages: {
    AUTH_SUCCESS: 'auth-success',
    SESSION_GET: 'session-get',
    SESSION_EDIT: 'session-edit',
    SETTINGS_SET: 'settings-set',
    SETTINGS_DELETE: 'settings-delete',
    SETTINGS_GET: 'settings-get',
    SETTINGS_CLEAR: 'settings-clear',
    REMOVE_PAGES_FROM_CACHE: 'remove-pages-from-cache',
    AUTO_CART: 'auto-cart',
    REMOVE_UNSAVED_SESSIONS: 'remove-unsaved-sessions',
    SET_MASTER_PASSWORD: 'set-master-password',
    GET_USER: 'get-user',
    REFRESH_IP: 'refresh-ip',
    EDIT_PROXY: 'edit-proxy',
    LOAD_SESSION: 'load-session',
    CLEAR_COOKIES: 'clear-cookies',
    CLEAR_COOKIES_EVENUE: 'clear-cookies-evenue',
    TOGGLE_PROXY_IN_SESSION: 'toggle-proxy-in-session',
    TOGGLE_PROXY_LOCATION: 'toogle-proxy-location',
    TOGGLE_PROXY_GLOBALLY: 'toggle-proxy-globally',
    SET_COOKIES: 'set-cookies',
    TAB_CONTEXT_MENU: 'tab-context-menu',
    WEBVIEW_CONTEXT_MENU: 'webview-context-menu',
    ADDRESS_BAR_CONTEXT_MENU: 'address-bar-context-menu',
    OPEN_LINK_OPENING_DIALOG: 'open-link-opening-dialog',
    OPEN_DELETE_SESSIONS_DIALOG: 'open-delete-sessions-dialog',
    OPEN_EDIT_SESSIONS_DIALOG: 'open-edit-sessions-dialog',
    OPEN_ADD_SESSIONS_DIALOG: 'open-add-sessions-dialog',
    SET_TAB_TIMER: 'set-tab-timer',
    ON_SMS: 'on-sms',
    AUTO_FILL_SMS: 'on-auto-fill-sms',
    SHOW_NOTIFICATION: 'show-notification',
    SET_AUTO_FILL_POPUP: 'open-auto-fill-popup',
    GET_AND_AUTO_FILL_PAYMENT_DATA: 'get-and-auto-fill-payment-data',
    FILL_PAYMENT_DATA_IN_IFRAME: 'fill-payment-data-in-iframe',
    FILL_SUGGESTED_PASSWORD: 'fill-suggested-password',
    FRAME_LOADED: 'frame-loaded',
    EDIT_PAGE_SITE_CREDENTIALS: 'edit-page-site-credentials',
    SUGGEST_TO_SAVE_SITE_CREDENTIALS: 'suggest-to-save-site-credentials',
    FILL_LOGIN: 'auto-fill-login',
    HAS_COOKIES_CHANGED: 'has-cookies-changed',
  }
};

module.exports = consts;
